export const API_ENDPOINTS = {
  AUTH: {
    REGISTER: '/auth/register',
    LOGIN: '/auth/login',
    VERIFY_EMAIL: (token: string) => `/auth/verify-email/${token}`,
    GOOGLE_LOGIN: '/auth/google-login',
    REFRESH: '/auth/refresh',
  },
  USERS: {
    PROFILE: (userId: string) => `/api/users/profile/${userId}`,
    PASSWORD: (userId: string) => `/api/users/password/${userId}`,
  },
  TRIPS: {
    BASE: '/api/plantrips',
    ALL: '/api/plantrips/all',
    USER_TRIPS: (userId: string) => `/api/plantrips/user/${userId}`,
    DETAILS: (tripId: string) => `/api/plantrips/${tripId}`,
    CHAT: (tripId: string) => `/api/plantrips/${tripId}/chat`,
    FINALIZE: (tripId: string) => `/api/plantrips/${tripId}/finalize`,
    CANCEL: (tripId: string) => `/api/plantrips/${tripId}/cancel`,
    COMPLETE: (tripId: string) => `/api/plantrips/${tripId}/complete`,
    UPDATE_GUIDE: (tripId: string) => `/api/plantrips/${tripId}/guide`,
    GUIDE_TRIPS: (guideId: string) => `/api/plantrips/guide/${guideId}`,
  },
  AI: {
    CHAT: '/api/ai/chat',
  },
  REPORTS: {
    BASE: '/api/reports',
    ALL: '/api/reports/all',
    STATUS: (reportId: string) => `/api/reports/${reportId}/status`,
    TARGET: (targetId: string) => `/api/reports/target/${targetId}`,
  },
  PAYMENTS: {
    CREATE_STRIPE_SESSION: '/api/payments/create-stripe-session',
    VERIFY_STRIPE_PAYMENT: '/api/payments/verify-stripe-payment',
    PAY_DEPOSIT: '/api/payments/pay-deposit',
    PAY_WITH_WALLET: '/api/payments/pay-with-wallet',
    MY_PAYMENTS: (tripId: string) => `/api/payments/my-payments/${tripId}`,
    TRIP_PAYMENTS: (tripId: string) => `/api/payments/trip-payments/${tripId}`,
    USER_PAYMENTS: '/api/payments/user-payments',
    WALLET_TRANSACTIONS: '/api/payments/wallet-transactions',
  },
  GUIDES: {
    PROFILE: '/api/guides/profile',
    STATUS: (userId: string) => `/api/guides/status/${userId}`,
    ALL: '/api/guides/all',
  },
  GUIDE_INVITATIONS: {
    SEND: '/api/guide-invitations/send',
    INBOUND: '/api/guide-invitations/inbound',
    RESPOND: '/api/guide-invitations/respond',
  },
  GALLERY: {
    UPLOAD: '/api/gallery/upload',
    POST: '/api/gallery/post',
    ALL: '/api/gallery/all',
    USER_GALLERY: (userId: string) => `/api/gallery/user/${userId}`,
  },
  EXPENSES: {
    BASE: '/api/expenses',
    TRIP_EXPENSES: (tripId: string) => `/api/expenses/trip/${tripId}`,
    DELETE: (expenseId: string) => `/api/expenses/${expenseId}`,
  },
  CONNECTIONS: {
    REQUEST: '/api/connections/request',
    STATUS: '/api/connections/status',
    PENDING: '/api/connections/pending',
    MY_REQUESTS: '/api/connections/my-requests',
    ACCEPT: (requestId: string) => `/api/connections/accept/${requestId}`,
    REJECT: (requestId: string) => `/api/connections/reject/${requestId}`,
    MEMBERS: (tripId: string) => `/api/connections/members/${tripId}`,
  },
  ADMIN: {
    GUIDES: '/api/admin/guides',
    VERIFY_GUIDE: (id: string) => `/api/admin/guides/${id}/verify`,
    UPDATE_GUIDE: (id: string) => `/api/admin/guides/${id}`,
    USERS: '/api/admin/users',
    BLOCK_USER: (id: string) => `/api/admin/users/${id}/block`,
    APPROVE_KYC: (userId: string) => `/api/admin/kyc/${userId}/approve`,
    TRIPS: '/api/admin/trips',
    UPDATE_TRIP_STATUS: (tripId: string) => `/api/admin/trips/${tripId}/status`,
    REVENUE_STATS: '/api/admin/revenue/stats',
    PAYMENTS: '/api/admin/payments',
    UPDATE_PAYMENT_STATUS: (id: string) => `/api/admin/payments/${id}/status`,
    DELETE_USER: (id: string) => `/api/admin/users/${id}`,
  },
  REVIEWS: {
    GUIDE_REVIEWS: (guideId: string) => `/api/reviews/guide/${guideId}`,
    ADMIN_ALL: '/api/reviews/admin/all',
    DETAILS: (reviewId: string) => `/api/reviews/${reviewId}`,
    TRIP_REVIEWS: (tripId: string) => `/api/reviews/trip/${tripId}`,
  },
  KYC: {
    STATUS: (userId: string) => `/api/kyc-status/${userId}`,
    UPLOAD: '/api/upload',
  },
  MISC: {
    PROFILE_PHOTO: '/api/profile-photo',
    CHAT_IMAGE: '/api/chat-image',
    FORGOT_PASSWORD: '/api/users/forgot-password',
    RESET_PASSWORD: (token: string) => `/api/users/reset-password/${token}`,
    GUIDE_REGISTER: '/api/guides/register',
    RESET_GUIDE_STATUS: '/api/guides/reset-status',
    OUTBOUND_INVITATIONS: '/api/guide-invitations/outbound',
  },
  EXTERNAL_SERVICES: {
    NOMINATIM: 'https://nominatim.openstreetmap.org/search',
    OPEN_METEO: 'https://api.open-meteo.com/v1/forecast',
    OVERPASS: 'https://overpass-api.de/api/interpreter',
  },
};
